require("kenz.plugins-setup")
require("kenz.core.options")
require("kenz.core.keymaps")
require("kenz.core.colorscheme")

require("kenz.plugins.comment")
require("kenz.plugins.nvim-tree")
require("kenz.plugins.lualine")
require("kenz.plugins.telescope")
require("kenz.plugins.nvim-cmp")
require("kenz.plugins.lsp.mason")
require("kenz.plugins.lsp.lspsaga")
require("kenz.plugins.lsp.lspconfig")
require("kenz.plugins.lsp.null-ls")
require("kenz.plugins.autopairs")
require("kenz.plugins.treesitter")
require("kenz.plugins.gitsigns")
require("kenz.plugins.dap-config")
